data = {
    'US_STATES_QUIZ': {
        'STATES': {
            'Alabama': 'Montgomery',
            'Alaska': 'Juneau',
            'Arizona': 'Phoenix',
            'Arkansas': 'Little Rock',
            'California': 'Sacramento',
            'Colorado': 'Denver',
            'Connecticut': 'Hartford',
            'Delaware': 'Dover',
            'Florida': 'Tallahassee',
            'Georgia': 'Atlanta',
            'Hawaii': 'Honolulu',
            'Idaho': 'Boise',
            'Illinois': 'Springfield',
            'Indiana': 'Indianapolis',
            'Iowa': 'Des Moines',
            'Kansas': 'Topeka',
            'Kentucky': 'Frankfort',
            'Louisiana': 'Baton Rouge',
            'Maine': 'Augusta',
            'Maryland': 'Annapolis',
            'Massachusetts': 'Boston',
            'Michigan': 'Lansing',
            'Minnesota': 'Saint Paul',
            'Mississippi': 'Jackson',
            'Missouri': 'Jefferson City',
            'Montana': 'Helena',
            'Nebraska': 'Lincoln',
            'Nevada': 'Carson City',
            'New Hampshire': 'Concord',
            'New Jersey': 'Trenton',
            'New Mexico': 'Santa Fe',
            'New York': 'Albany',
            'North Carolina': 'Raleigh',
            'North Dakota': 'Bismarck',
            'Ohio': 'Columbus',
            'Oklahoma': 'Oklahoma City',
            'Oregon': 'Salem',
            'Pennsylvania': 'Harrisburg',
            'Rhode Island': 'Providence',
            'South Carolina': 'Columbia',
            'South Dakota': 'Pierre',
            'Tennessee': 'Nashville',
            'Texas': 'Austin',
            'Utah': 'Salt Lake City',
            'Vermont': 'Montpelier',
            'Virginia': 'Richmond',
            'Washington': 'Olympia',
            'West Virginia': 'Charleston',
            'Wisconsin': 'Madison',
            'Wyoming': 'Cheyenne'
        },
        'QUIZ_TOPIC': 'Quiz stolic Stanów Zjednoczonych',
        'QUIZ_QUESTION': 'Co jest stolicą Stanu',
        'COUNTRY_CODE': '-us',
        'FILE_NAME': 'capitals_quiz',

    },
    'PL_DISTRICT_QUIZ': {
        'DISTRICTS': {
            'Dolnośląskie': 'Wrocław',
            'Kujawsko-Pomorskie': 'Toruń',
            'Lubelskie': 'Lublin',
            'Lubuskie': 'Zielona Góra',
            'Łódzkie': 'Łódź',
            'Małopolskie': 'Kraków',
            'Mazowieckie': 'Warszawa',
            'Opolskie': 'Opole',
            'Podkarpackie': 'Rzeszów',
            'Podlaskie': 'Białystok',
            'Pomorskie': 'Gdańsk',
            'Śląskie': 'Katowice',
            'Świętokrzyskie': 'Kielce',
            'Warmińsko-Mazurskie': 'Olsztyn',
            'Wielkopolskie': 'Poznań',
            'Zachodniopomorskie': 'Szczecin',
        },
        'QUIZ_TOPIC': 'Quiz stolic województw Polski',
        'QUIZ_QUESTION': 'Co jest stolicą województwa',
        'FILE_NAME': 'district_quiz',
        'COUNTRY_CODE': '-pl',
        'VERBOSE_NAME_SUFFIX': 'go',
    },

}
